"""
make_table_mismatch.py
----------------------
Emit sim/results/table_mismatch.tex (booktabs) with 8 rows:
  bias 0, 2, 5, 10 (m)
  factor 1, 2, 4, 8
Columns: scenario, knob value, SensLyap CVaR, DRCVaRLyap CVaR,
         SensLyap exceedance (viol_rate), DRCVaRLyap exceedance.
"""
from __future__ import annotations
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results", "exp_mismatch.json")
TEX_OUT = os.path.join(HERE, "results", "table_mismatch.tex")


def _fmt(x: float, dec: int = 1) -> str:
    return f"{x:.{dec}f}"


def main():
    with open(RESULTS) as f:
        d = json.load(f)

    bias_values = d["_meta"]["bias_values_m"]
    factor_values = d["_meta"]["factor_values"]

    rows = []
    for b in bias_values:
        cell = d.get(f"bias={float(b)}", {})
        sl = cell.get("SensLyap", {})
        dr = cell.get("DRCVaRLyap", {})
        rows.append((
            "bias",
            f"{int(b) if b == int(b) else b}\\,m",
            sl.get("cvar_beta", {}).get("mean", float("nan")),
            dr.get("cvar_beta", {}).get("mean", float("nan")),
            sl.get("viol_rate", {}).get("mean", float("nan")),
            dr.get("viol_rate", {}).get("mean", float("nan")),
        ))
    for fac in factor_values:
        cell = d.get(f"factor={float(fac)}", {})
        sl = cell.get("SensLyap", {})
        dr = cell.get("DRCVaRLyap", {})
        rows.append((
            "factor",
            f"{int(fac) if fac == int(fac) else fac}$\\times$",
            sl.get("cvar_beta", {}).get("mean", float("nan")),
            dr.get("cvar_beta", {}).get("mean", float("nan")),
            sl.get("viol_rate", {}).get("mean", float("nan")),
            dr.get("viol_rate", {}).get("mean", float("nan")),
        ))

    lines = []
    lines.append("% Auto-generated by sim/make_table_mismatch.py")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\begin{tabular}{llcccc}")
    lines.append("\\toprule")
    lines.append("Scenario & Value & "
                 "\\multicolumn{2}{c}{CVaR$_{0.95}(\\ell)$} & "
                 "\\multicolumn{2}{c}{$\\Pr(\\ell>\\Gamma)$} \\\\")
    lines.append("\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}")
    lines.append(" & & Sens-Lyap & DR-CVaR & Sens-Lyap & DR-CVaR \\\\")
    lines.append("\\midrule")
    prev_kind = None
    for kind, val, slC, drC, slV, drV in rows:
        if prev_kind is not None and kind != prev_kind:
            lines.append("\\midrule")
        prev_kind = kind
        # Bold the better CVaR
        slC_s = _fmt(slC, 1)
        drC_s = _fmt(drC, 1)
        if slC < drC:
            slC_s = "\\textbf{" + slC_s + "}"
        elif drC < slC:
            drC_s = "\\textbf{" + drC_s + "}"
        slV_s = _fmt(slV, 3)
        drV_s = _fmt(drV, 3)
        if slV < drV:
            slV_s = "\\textbf{" + slV_s + "}"
        elif drV < slV:
            drV_s = "\\textbf{" + drV_s + "}"
        kind_lbl = "bias $b$" if kind == "bias" else "$\\sigma$ factor"
        lines.append(f"{kind_lbl} & {val} & {slC_s} & {drC_s} & "
                     f"{slV_s} & {drV_s} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    with open(TEX_OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {TEX_OUT}")


if __name__ == "__main__":
    main()
